### ISSUE TITLE
Auto Smite Script

### ISSUE THREAD

**Issue by LeonardoFBR** [botkalista/ayaya-league-external#10]
Hello, could you tell me or give me an idea of how I could make a smite script?

**Comment by botkalista** [comment]
> Hello, could you tell me or give me an idea of how I could make a smite script?

You should do these steps i guess:
- check if the dragon has hp <= 900 or hp <= 450
- check if the smite is up
- move mouse on dragon
- press smite button

**Comment by LeonardoFBR** [comment]
I will try, thank you
