### ISSUE TITLE
orb and evade not working 

### ISSUE THREAD

**Issue by ssuawf** [botkalista/ayaya-league-external#12]
(node:7532) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `AyayaLeague --trace-warnings ...` to show where the warning was created)

[20408:0812/093216.109:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by botkalista** [comment]
> (node:7532) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. (Use `AyayaLeague --trace-warnings ...` to show where the warning was created)
> 
> [20408:0812/093216.109:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

That's just a warning. You need to edit `SimpleEvade.js` and `Orbwalker.js`.
Please read carefully the **readme.md**
