### ISSUE TITLE
Any solution for this problem?

### ISSUE THREAD

**Issue by LeonardoFBR** [botkalista/ayaya-league-external#13]
![fcf81cbe7363b2efc81e8e377c3a6d5d](https://user-images.githubusercontent.com/72281630/184458155-cc0e57b4-ad2b-4be6-86b7-9f2c7b44c9b7.png)

**Comment by LeonardoFBR** [comment]
I was able to solve it, for those who have the same problem. There are some files missing in the source version

**Comment by LeonardoFBR** [comment]
![a671fdecc8b465515bbba40bd5e83dc0](https://user-images.githubusercontent.com/72281630/184472342-01e78664-659b-49ac-ba2a-fc46a7a6daa0.png)

**Comment by LeonardoFBR** [comment]
Just copy the build folder and it will work.

**Comment by NiceLeader** [comment]
look in previous issues #7

**Comment by LeonardoFBR** [comment]
There is no solution in this thread. However the problem is that a folder containing the missing files is missing.

**Comment by LeonardoFBR** [comment]
![a671fdecc8b465515bbba40bd5e83dc0](https://user-images.githubusercontent.com/72281630/184478800-c9069eb8-a34a-4fb3-ac01-a0c3f14468aa.png)

**Comment by LeonardoFBR** [comment]
You only need to pass the build file from the release to the source.

**Comment by LeonardoFBR** [comment]
With that I was able to make it work

**Comment by botkalista** [comment]
> ![fcf81cbe7363b2efc81e8e377c3a6d5d](https://user-images.githubusercontent.com/72281630/184458155-cc0e57b4-ad2b-4be6-86b7-9f2c7b44c9b7.png)

You extracted the files from the zip ?

**Comment by LeonardoFBR** [comment]
I did all the steps indicated in the guide from git clone

**Comment by LeonardoFBR** [comment]
And it didn't work until I copied the build folder of the releases.
