### ISSUE TITLE
Auto Smite Script

### ISSUE THREAD

**Issue by LeonardoFBR** [botkalista/ayaya-league-external#14]
let canSmite = false;
let actived = false;

const sleep = (milliseconds) => {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
};

function setup() {
  console.log("AutoSmite.js loaded.");
}

/**
 * @param {import("../UserScriptManager").UserScriptManager} manager ScriptManager
 * @param {number} ticks Ticks counter
 *
 * This JSDOC is optional, it's only purpose is to add intellisense while you write the script
 *
 * */

async function onTick(manager, ticks) {
  const active = manager.game.isKeyPressed(0x61); // 0x4E = N | 0x5 = MouseButtonX | 0x20 = SPACE | 0x61 = Nump 1 | 0x62 = Nump 2
  const desactive = manager.game.isKeyPressed(0x62); // 0x4E = N | 0x5 = MouseButtonX | 0x20 = SPACE | 0x61 = Nump 1 | 0x62 = Nump 2

  if (active) {
    actived = true;
    console.log("Active");
  } else if (desactive) {
    actived = false;
    console.log("Desactive");
  }

  if (!actived) return;

  // Smite in D = 4 | Smite in F = 5

  if (manager.me.spells[4].ready == false) {
    canSmite = false;
    return;
  } else {
    canSmite = true;
  }

  if (canSmite == false) return;

  if (manager.me.spells[4].name == "SummonerSmite") {
    smiteDamage = 450;
  } else {
    smiteDamage = 900;
  }

  const targets = manager.monsters;
  if (targets.length == 0) return;
  let targets2 = [];

  for (let i = 0; i < targets.length; i++) {
    if (
      targets[i].name == "SRU_Baron" ||
      targets[i].name == "SRU_Dragon_Air" ||
      targets[i].name == "SRU_Dragon_Fire" ||
      targets[i].name == "SRU_Dragon_Water" ||
      targets[i].name == "SRU_Dragon_Earth" ||
      targets[i].name == "SRU_Dragon_Elder" ||
      targets[i].name == "SRU_RiftHerald" ||
      targets[i].name == "SRU_Dragon_Chemtech" ||
      targets[i].name == "SRU_Dragon_Hextech"
    ) {
      targets2.push(targets[i]);
    }
  }

  const closestInRange = targets2.reduce(
    (p, e) => {
      const dist = Math.hypot(
        e.screenPos.x - manager.me.screenPos.x,
        e.screenPos.y - manager.me.screenPos.y
      );
      const pRange = manager.me.range;
      const eBoundingBox = manager.me.boundingBox;
      return dist < pRange / 2 + eBoundingBox * 2 && dist < p.d
        ? { d: dist, e }
        : p;
    },
    { d: 999, e: targets2[0] }
  );

  if (closestInRange.d == 999) return;
  if (closestInRange.e.hp <= 0) return;

  if (closestInRange.e.hp <= smiteDamage) {
    const oldMousePos = manager.game.getMousePos();
    manager.game.setMousePos(
      closestInRange.e.screenPos.x,
      closestInRange.e.screenPos.y
    );
    manager.game.pressKey(manager.spellSlot.D);
    await sleep(278);
    manager.game.releaseKey(manager.spellSlot.D);
    manager.game.setMousePos(oldMousePos.x, oldMousePos.y);
    canSmite = false;
    23;
  }
}

/**
 * @param {import("../../src/models/Missile").Missile} missile Missile
 * @param {import("../UserScriptManager").UserScriptManager} manager ScriptManager
 *
 * This JSDOC is optional, it's only purpose is to add intellisense while you write the script
 *
 * */
function onMissileCreate(missile, manager) {
  return;
}

module.exports = { setup, onTick, onMissileCreate };

**Comment by LeonardoFBR** [comment]
I'm not very good at programming, but it's worth a try haha

**Comment by LeonardoFBR** [comment]
I'm not very good at programming, but I'm doing my best haha.

**Comment by LeonardoFBR** [comment]
@botkalista

**Comment by botkalista** [comment]
> @botkalista

Did you test it ?
Also, i guess you should use `underMouseObject` and check if that object is a neutral monster

**Comment by LeonardoFBR** [comment]
I have played several games already, tried it in practice tool and in qualifying games. All perfect.

**Comment by LeonardoFBR** [comment]
![WhatsApp Video 2022-08-13 at 2 09 12 PM](https://user-images.githubusercontent.com/72281630/184507621-257bede9-619f-474f-a03c-8df4dc7afc40.gif)

**Comment by LeonardoFBR** [comment]
@botkalista Is there any way to know the damage of spells?

**Comment by botkalista** [comment]
> @botkalista Is there any way to know the damage of spells?

You must create your own spells db with all parameters.

I read you script, this is the same but with my style of coding.

I'm glad you are experimenting things creating user scripts, add me on discord please `~Zoe~#1961`

```js
/**
 * @typedef {import("../UserScriptManager").UserScriptManager} Manager
 * @typedef {import("../../src/events/types").ScriptSettings} Settings
 * @typedef {import("../UserScriptManager").UserScriptManager} Manager
 */

const neutralsTargets = [
    "SRU_Baron",
    "SRU_Dragon_Air",
    "SRU_Dragon_Fire",
    "SRU_Dragon_Water",
    "SRU_Dragon_Earth",
    "SRU_Dragon_Elder",
    "SRU_RiftHerald",
    "SRU_Dragon_Chemtech",
    "SRU_Dragon_Hextech"
]

const smites = {
    SummonerSmite: 450,
    S5_SummonerSmiteDuel: 900,
    S5_SummonerSmitePlayerGanker: 900
}

function getSmite(manager) {
    const smite = manager.spells.find(e => e.name.includes('SummonerSmite'));
    return smite;
}

function setup() {
    console.log("AutoSmite.js loaded.");

    const settings = [
        { type: 'check', defalue: false, text: 'Active' }
    ]

    return settings;
}

/**

 * @param {Manager} manager 
 * @param {*} ticks 
 * @param {Settings} settings 
 * @returns 
 */
async function onTick(manager, ticks, settings) {

    if (!settings[0].value) return;

    const smite = getSmite(manager);
    if (!smite.ready) return;

    const targets = manager.monsters.filter(e => neutralsTargets.includes(e.name));
    if (targets.length == 0) return;

    const closestInRange = targets2.reduce((p, e) => {
        const dist = Math.hypot(
            e.screenPos.x - manager.me.screenPos.x,
            e.screenPos.y - manager.me.screenPos.y
        );
        const pRange = manager.me.range;
        const eBoundingBox = manager.me.boundingBox;
        return dist < pRange / 2 + eBoundingBox * 2 && dist < p.d ? { d: dist, e } : p;
    }, { d: 999, e: targets[0] });

    if (closestInRange.d == 999) return;
    if (closestInRange.e.hp <= 0) return;

    if (closestInRange.e.hp <= smites[smite]) {
        const oldMousePos = manager.game.getMousePos();
        manager.game.setMousePos(closestInRange.e.screenPos.x, closestInRange.e.screenPos.y);
        manager.game.pressKey(manager.spellSlot.D);
        manager.game.sleep(35);
        manager.game.releaseKey(manager.spellSlot.D);
        manager.game.setMousePos(oldMousePos.x, oldMousePos.y);
    }
}

module.exports = { setup, onTick };
```
