### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by myo** [botkalista/ayaya-league-external#15]
https://github.com/botkalista/ayaya-league-external/blob/master/src/ActionControllerWrapper.ts#L26

you can return an Napi::Object instead of a string

**Comment by botkalista** [comment]
> https://github.com/botkalista/ayaya-league-external/blob/master/src/ActionControllerWrapper.ts#L26
> 
> you can return an Napi::Object instead of a string

Ye, i read something about Napi::Object but i have no clue how to use them xD

**Comment by myo** [comment]
this is mine

Napi::Value getMouseLocation(const Napi::CallbackInfo &args)
{
  Napi::Env env = args.Env();

  int *result = IO::GetMouseLocation();

  Napi::Object ret = Napi::Object::New(env);
  ret.Set("x", *result);
  ret.Set("y", *(result+1));
  return ret;
}

**Comment by myo** [comment]
Also 
https://github.com/botkalista/ayaya-league-external/blob/master/scripts/userscripts/Orbwalker.js#L59
I understand you really don't like if blocks, but maybe just this instance you could pass Vector2.zero, and check in issueOrder if it's Vector2.zero, or create separate issueAttack and issueMovement

**Comment by botkalista** [comment]
> I understand you really don't like if blocks

That's 100% me xD

> because you are moving it back to original position after attack: https://github.com/botkalista/ayaya-league-external/blob/master/src/models/Game.ts#L101

Orbwalker.js is an old file, i think it's not even working with the new AyayaLeague version
