### ISSUE TITLE
Are there any banned acc bc of ayaya?

### ISSUE THREAD

**Issue by NiceLeader** [botkalista/ayaya-league-external#16]

**Comment by botkalista** [comment]
Still zero bans. It's kinda hard to detect and also i followed the Riot Terms of Service:
- No memory writes
- No calls on internal functions
- No use of expoits

**Comment by myo** [comment]
Riot knows you are opening a handle to read from the game memory, they know you are using a fake mouse and keyboard (methods used by this cheat set the LLKHF_INJECTED flag, google it), and a lot more small things.

Will they ban you for any of this? No one knows. At the moment they didn't even ban winstealer users **yet**. It's probably not smart to use any cheat on an account you can't afford losing though.

**Comment by vacnex** [comment]
Is reading the game's memory dangerous?

**Comment by myo** [comment]
No, reading memory is not dangerous. Most apps on overwolf probably use memoryjs just like this platform.

I was just saying Riot anticheat devs weren't born yesterday, they are hackers themselves, so the only way to be sure you don't get your account banned is to not cheat.
