### ISSUE TITLE
manager(UserScriptManager).playerState is undefined

### ISSUE THREAD

**Issue by myo** [botkalista/ayaya-league-external#18]
async function onTick(manager, settings) {
    if (manager.playerState != "idle") {
        console.log(manager.playerState); //logs undefined
        return;
    }
}

**Comment by botkalista** [comment]
> async function onTick(manager, settings) { if (manager.playerState != "idle") { console.log(manager.playerState); //logs undefined return; } }

That's right, since no script ever set playerState it starts as undefined

**Comment by myo** [comment]
I set it to idle in loadUserScripts (src/index.ts), opened the issue because I thought this was not intended.
