### ISSUE TITLE
Misaligned Visuals

### ISSUE THREAD

**Issue by Hollowcard565** [botkalista/ayaya-league-external#19]
![Untitled](https://user-images.githubusercontent.com/93537278/184786788-18f7bf73-703b-4bea-b5cc-62c03250edfb.png)

Additional Details 
Resolution: 1920 x 1080
Scale: 100%

**Comment by botkalista** [comment]
> ![Untitled](https://user-images.githubusercontent.com/93537278/184786788-18f7bf73-703b-4bea-b5cc-62c03250edfb.png)
> 
> Additional Details Resolution: 1920 x 1080 Scale: 100%

Another user had the same problem, that was caused by the text dimention in windows settings, check if that value is set at 100%.
https://support.microsoft.com/en-us/windows/make-text-and-apps-bigger-c3095a80-6edd-4779-9282-623c4d721d64

**Comment by Hollowcard565** [comment]
Fixed with this solution ^ ! :)
