### ISSUE TITLE
the program runs but no script is executed, and you don't see the lines or anything

### ISSUE THREAD

**Issue by Mister20143** [botkalista/ayaya-league-external#2]
If someone could help me I would be very grateful

image with the problem
https://imgur.com/a/UkFExVS

**Comment by myo** [comment]
You'll have to make a small edit
https://github.com/botkalista/ayaya-league-external/pull/1/commits/55d084ac8485dd01ffaad5a9d88efe7841acc261

and follow the setup instructions
https://github.com/botkalista/ayaya-league-external#how-to-setup-and-run

specifically #4.

If you did run npm i(nstall) then it could be a problem with the path being too long, try either renaming ayaya-league-external folder to something shorter or moving it one level up (into the downloads folder or something)

**Comment by botkalista** [comment]
i updated readme.md in last commit
- fixed worldToScreen error
- setup is easier (doesn't require 2 nodes versions)

Please notice that this platform is still in Alpha so there will be a lot on commits in short time.
