### ISSUE TITLE
Running program crash

### ISSUE THREAD

**Issue by YMY1666527646** [botkalista/ayaya-league-external#32]
PS C:\Windows\system32>
ELECTRON 20.0.1 NODE 16.15.0 ia32
Loading scripts
Scripts loaded
CHANGED true
Opening league process
Core loaded
Debug loaded
Starting loop on reenderer

#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 75209227
#
#
#
#FailureMessage Object: 0EFFE2A4
 1: 01DE7EDC node_api_get_module_file_name+16668
 2: 04CA50E9 Cr_z_zError+1531993
 3: 001F215C v8::Extension::set_auto_enable+2300
 4: 00AD6D09 v8::CppHeap::GetAllocationHandle+502073
 5: 03F4B102 v8::Platform::SystemClockTimeMillis+179682
 6: 00B3B546 v8::CppHeap::GetAllocationHandle+913782
 7: 03132FB7 cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::IsMarking+1885847

**Comment by botkalista** [comment]
AyayaLeague version ?
Also, why are you starting it from system32 ?

**Comment by YMY1666527646** [comment]
> AyayaLeague version ? Also, why are you starting it from system32 ?

I tried many times, and the right-click administrator also crashed the program. I entered the game without a border

**Comment by botkalista** [comment]
> AyayaLeague version ?

**Comment by YMY1666527646** [comment]
Yes, I downloaded your yaya-league-2.0.2
https://github.com/botkalista/ayaya-league-external/releases/tag/12.16_2.0.4_preview

**Comment by Hidend** [comment]
in what server are you using it? because you seem CN and this is not made for it

**Comment by YMY1666527646** [comment]
> in what server are you using it? because you seem CN and this is not made for it

I use it on a server in China

**Comment by YMY1666527646** [comment]
Ayayaleague can it be used on Chinese servers?
