### ISSUE TITLE
Not working in 12.7.

### ISSUE THREAD

**Issue by juunr95** [botkalista/ayaya-league-external#40]
Is any update in way ?

**Comment by myo** [comment]
author is asking for money on his ko-fi to continue updating this software:
https://ko-fi.com/ayayaleague

**Comment by myo** [comment]
author is asking for money on their ko-fi to continue updating this software:
https://ko-fi.com/ayayaleague

**Comment by juunr95** [comment]
I'll try to update the offsets for this

**Comment by myo** [comment]
I mean you could, but the platform needs serious work, the 2.0 version (which is actually fire) is so unfinished it hurts.

That's why I'm waiting for people to donate/the developer to refind his passion of building this little project.

**Comment by nyzss** [comment]
> I can update this now but it would be disrespectful to the developer I don't want that to happen so you have to wait for the developer to update and release it ;)

Nothing disrespectful imo, just make a pull request or simply share the new offsets, if someone knows what to do with the new offsets I'm pretty they already updated their own fork.

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189401597-d2b88d2f-2885-4c48-a7eb-a1c291ad6cce.png)

Almost done

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189402255-89994b69-ecac-4118-9986-0e261795ea3b.png)

**Comment by sysbal** [comment]
Just updating spell offsets and i will share that shit for u guys

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189405356-5db0d5ab-e0f2-4a09-8447-5be08ed77a9e.png)

**Comment by sysbal** [comment]
Almost done updating offsets

**Comment by yacine12345l** [comment]
> Almost done updating offsets

where can we get it please !

**Comment by juunr95** [comment]
What tool are you using to search address ?

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189431714-d535d04b-b2cf-4a01-bae6-86c37e615ed1.png)

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189432722-a2936a8f-cb8f-4c56-ba1e-941e23d35c5e.png)

**Comment by sysbal** [comment]
![image](https://user-images.githubusercontent.com/111451126/189434277-6788c6ea-6aed-454c-8e42-733f14ee5d16.png)
I will not share any updated offsets! But i really wanna to thanks the developer. Really . 
Its a great base of study

**Comment by sysbal** [comment]
Greets from Brazil my friend.

**Comment by yacine12345l** [comment]
oh :(

**Comment by juunr95** [comment]
OK thanks, you already show :)

**Comment by yacine12345l** [comment]
@juunr95 if u happen to update offsets can you please share with me

**Comment by YMY1666527646** [comment]
> ![image](https://user-images.githubusercontent.com/111451126/189434277-6788c6ea-6aed-454c-8e42-733f14ee5d16.png) I will not share any updated offsets! But i really wanna to thanks the developer. Really . Its a great base of study

This ayayaleague?
Ayayaleague can it be used on Chinese servers?

**Comment by IgorBraga21** [comment]
@YMY1666527646

How did you make the hack work? because I've been trying for a long time and I can't.
this hack menu does not appear, do i need to create my own .js to work?

**Comment by YMY1666527646** [comment]
> @YMY1666527646
> 
> How did you make the hack work? because I've been trying for a long time and I can't. this hack menu does not appear, do i need to create my own .js to work?

I am also puzzled, because I have not studied JS, and I only know a little c++

**Comment by sysbal** [comment]
> a
It will not work in chinese servers in the actual state. To work in  chinese server, u will need to unhook the protection of threads and call in injected dll. Disable the pattern scanner and some other shit.
Good luck

**Comment by YMY1666527646** [comment]
Are Chinese services thread protected so they can't be used?
I have a problem. I think I'd better give up. If you know any solutions, please let me know. Thank you. I will try or learn something else
![QQ截图20220910135916](https://user-images.githubusercontent.com/84628110/189471489-0fd9df62-f88e-4477-9180-a6e214ba6109.png)
![QQ截图20220910135940](https://user-images.githubusercontent.com/84628110/189471490-63aa3771-6a76-4ac2-ace0-ddc0dd874bca.png)

**Comment by juunr95** [comment]
I also update some offsets. Just trying to realize why ranges are out of player

**Comment by yacine12345l** [comment]
@juunr95 can you share ?

**Comment by yacine12345l** [comment]
please !

**Comment by sysbal** [comment]
> I also update some offsets. Just trying to realize why ranges are out of player
> 
> Edit: just run in full hd and works haha

Your problem was the windows default zoom! It probably was in 125 by default in screen settings on windows.

**Comment by botkalista** [comment]
offsets updated
