### ISSUE TITLE
can't run script

### ISSUE THREAD

**Issue by d4rkrr** [botkalista/ayaya-league-external#7]
every time i do npm start this pops up, 0 idea what i did wrong please help

scripts/UserScriptManager.ts:11:22 - error TS2307: Cannot find module 'sat' or its corresponding type declarations.

11 import * as SAT from 'sat';
                        ~~~~~

src/ActionControllerWrapper.ts:2:24 - error TS2307: Cannot find module 'child_process' or its corresponding type declarations.

2 import * as child from 'child_process';
                         ~~~~~~~~~~~~~~~

src/ActionControllerWrapper.ts:3:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

3 import * as path from 'path';
                        ~~~~~~

src/ActionControllerWrapper.ts:6:28 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

6 const AyayaWinapiWrapper = require('../../src/cpp/build/Release/AyayaWinapiWrapper');
                             ~~~~~~~

src/index.ts:1:1 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

1 process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0";
  ~~~~~~~

src/index.ts:3:25 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

3 console.log('ELECTRON', process.versions.electron, 'NODE', process.versions.node, 'ARCH', process.arch)
                          ~~~~~~~

src/index.ts:3:60 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

3 console.log('ELECTRON', process.versions.electron, 'NODE', process.versions.node, 'ARCH', process.arch)
                                                             ~~~~~~~

src/index.ts:3:91 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

3 console.log('ELECTRON', process.versions.electron, 'NODE', process.versions.node, 'ARCH', process.arch)
                                                                                            ~~~~~~~

src/index.ts:5:88 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.

5 import { BrowserWindow, app, ipcMain, globalShortcut, IpcMainEvent, WebContents } from 'electron';
                                                                                         ~~~~~~~~~~

src/index.ts:18:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

18 import * as path from 'path';
                         ~~~~~~

src/index.ts:19:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

19 import * as fs from 'fs';
                       ~~~~

src/index.ts:20:24 - error TS2307: Cannot find module 'child_process' or its corresponding type declarations.

20 import * as child from 'child_process';
                          ~~~~~~~~~~~~~~~

src/index.ts:21:24 - error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.

21 import * as fetch from 'node-fetch';
                          ~~~~~~~~~~~~

src/index.ts:24:5 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

24 if (process.argv[2] == 'nohook') {
       ~~~~~~~

src/index.ts:96:32 - error TS2304: Cannot find name '__dirname'.

96     const basePath = path.join(__dirname, '../../scripts/userscripts');
                                  ~~~~~~~~~

src/index.ts:105:31 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

105             const imp = await require(p);
                                  ~~~~~~~

src/index.ts:119:16 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

119         delete require.cache[script._modulename];
                   ~~~~~~~

src/LeagueReader.ts:6:23 - error TS2307: Cannot find module 'mathjs' or its corresponding type declarations.

6 import * as math from 'mathjs'
                        ~~~~~~~~

src/MemoryReader.ts:2:22 - error TS2307: Cannot find module 'memoryjs' or its corresponding type declarations.

2 import * as mem from 'memoryjs';
                       ~~~~~~~~~~

src/MemoryReader.ts:3:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

3 import * as fs from 'fs';
                      ~~~~

src/MemoryReader.ts:4:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

4 import * as path from 'path';
                        ~~~~~~

src/MemoryReader.ts:19:19 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

19     private dump: Buffer;
                     ~~~~~~

src/MemoryReader.ts:119:95 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

119     readProcessMemoryBuffer(address: number, size: number, fromBaseAddress: boolean = false): Buffer {
                                                                                                  ~~~~~~

src/models/Entity.ts:8:22 - error TS2307: Cannot find module 'sat' or its corresponding type declarations.

8 import * as SAT from 'sat';
                       ~~~~~

src/models/Missile.ts:6:22 - error TS2307: Cannot find module 'sat' or its corresponding type declarations.

6 import * as SAT from 'sat';
                       ~~~~~

src/overlay/Settings.ts:3:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

3 import * as fs from 'fs';
                      ~~~~

src/overlay/Windows.ts:2:31 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.

2 import { BrowserWindow } from 'electron';
                                ~~~~~~~~~~

src/StructureReader.ts:3:23 - error TS2307: Cannot find module 'mathjs' or its corresponding type declarations.

3 import * as math from 'mathjs';
                        ~~~~~~~~

src/utils/Utils.ts:2:23 - error TS2307: Cannot find module 'mathjs' or its corresponding type declarations.

2 import * as math from 'mathjs';
                        ~~~~~~~~


Found 29 errors in 11 files.

Errors  Files
     1  scripts/UserScriptManager.ts:11
     3  src/ActionControllerWrapper.ts:2
    13  src/index.ts:1
     1  src/LeagueReader.ts:6
     5  src/MemoryReader.ts:2
     1  src/models/Entity.ts:8
     1  src/models/Missile.ts:6
     1  src/overlay/Settings.ts:3
     1  src/overlay/Windows.ts:2
     1  src/StructureReader.ts:3
     1  src/utils/Utils.ts:2

**Comment by d4rkrr** [comment]
installed npm i --save-dev @types/node and then tried nmp start again and this is what happened
![image](https://user-images.githubusercontent.com/68623953/183552712-a7fa82f0-c938-42c6-891a-f666be5dd307.png)

**Comment by botkalista** [comment]
are you running `npm start` inside the main folder ?

**Comment by 15945663** [comment]
There is no hii has been done, has not been able to get it

**Comment by d4rkrr** [comment]
> are you running `npm start` inside the main folder ?

yes

**Comment by botkalista** [comment]
@d4rkrr clone the last version of the repo and try again

**Comment by 15945663** [comment]
Which is the home folder?

**Comment by Xaziel** [comment]
I'm also having the same problem
![image](https://user-images.githubusercontent.com/87484241/183826098-abf50467-845a-4cf3-a2cd-96105b9e0887.png)

**Comment by botkalista** [comment]
> I'm also having the same problem ![image](https://user-images.githubusercontent.com/87484241/183826098-abf50467-845a-4cf3-a2cd-96105b9e0887.png)

You need to open a league game before running AyayaLeague

**Comment by Xaziel** [comment]
> > I'm also having the same problem ![image](https://user-images.githubusercontent.com/87484241/183826098-abf50467-845a-4cf3-a2cd-96105b9e0887.png)
> 
> You need to open a league game before running AyayaLeague

is using this prone to getting banned?

**Comment by 15945663** [comment]
> are you running `npm start` inside the main folder ?
> 
> 是否在主文件夹中运行 npm start？
Which is the home folder?

**Comment by 15945663** [comment]
![QQ图片20220810145743](https://user-images.githubusercontent.com/103008810/183835718-aa937a8f-fd20-4000-b9b5-0cbc8a663e7d.png)

**Comment by Xaziel** [comment]
> > I'm also having the same problem ![image](https://user-images.githubusercontent.com/87484241/183826098-abf50467-845a-4cf3-a2cd-96105b9e0887.png)
> 
> You need to open a league game before running AyayaLeague

![Screenshot (23)](https://user-images.githubusercontent.com/87484241/183850491-a1e6a115-c6ef-4e44-b9e7-e95ac2a28bfc.png)
I already tried it and it worked, and for some reason when I changed it to 50 it became an error!

**Comment by botkalista** [comment]
Loo

> > > I'm also having the same problem ![image](https://user-images.githubusercontent.com/87484241/183826098-abf50467-845a-4cf3-a2cd-96105b9e0887.png)
> > 
> > 
> > You need to open a league game before running AyayaLeague
> 
> ![Screenshot (23)](https://user-images.githubusercontent.com/87484241/183850491-a1e6a115-c6ef-4e44-b9e7-e95ac2a28bfc.png) I already tried it and it worked, and for some reason when I changed it to 50 it became an error!

Looks like you deleted some files inside `/app/dist/src` folder

**Comment by 15945663** [comment]
> 

Too many questions, can you make a tutorial video?

**Comment by botkalista** [comment]
> > 
> 
> Too many questions, can you make a tutorial video?

The readme is pretty detailed about every step to floow in order to make it work
