### ISSUE TITLE
Orbwalker fail

### ISSUE THREAD

**Issue by LeonardoFBR** [botkalista/ayaya-league-external#8]
Orbwalker is not working

**Comment by botkalista** [comment]
> Orbwalker is not working

You should modify the script, it was for an older version. Try to use the version i just pushed on the main branch. Thx.

**Comment by LeonardoFBR** [comment]
What a great job, I will study it

**Comment by LeonardoFBR** [comment]
![23691dbeebeb0b6dfa0beb2c070b2e75](https://user-images.githubusercontent.com/72281630/184054671-758c940a-3e03-4676-bba4-a972810ee2f6.png)

**Comment by LeonardoFBR** [comment]
How can I solve it?

**Comment by 15945663** [comment]
Too many questions, can you make a tutorial video?

**Comment by botkalista** [comment]
> How can I solve it?

Looks like you forgot to run `npm run check-dependencies`
Alternatively you can install that specific package running `npm i node-fetch@2.6.1`

**Comment by botkalista** [comment]
> Too many questions, can you make a tutorial video?

Refer to the reply at #7
