### ISSUE TITLE
evade can't work

### ISSUE THREAD

**Issue by Zukamiri** [botkalista/ayaya-league-external#9]
I don't see anything related to "Evade". The character also doesn't dodge

**Comment by botkalista** [comment]
> Zukamiri

Edit the file `SimpleEvade.js` as mentioned in the readme

**Comment by Zukamiri** [comment]
> > Zukamiri
> 
> Edit the file `SimpleEvade.js` as mentioned in the readme

Can u create a Simple Evade? i don't know how to edit

**Comment by botkalista** [comment]
> > > Zukamiri
> > 
> > 
> > Edit the file `SimpleEvade.js` as mentioned in the readme
> 
> Can u create a Simple Evade? i don't know how to edit

The readme is pretty detailed abot this, as i mentioned here https://github.com/botkalista/ayaya-league-external/issues/7#issuecomment-1211755294
